# Generated by Django 4.2.7 on 2023-12-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('AND', 'ANDAMENTO'), ('REP', 'REPROVADO'), ('INT', 'INTEGRADO'), ('PEN', 'PENDENTE')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
