# Generated by Django 4.2.7 on 2023-12-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_proposta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposta',
            name='telefone',
        ),
        migrations.AddField(
            model_name='proposta',
            name='operacao',
            field=models.CharField(choices=[('NOVO', 'NOVO'), ('REFIN', 'REFIN'), ('PORTABILIDADE', 'PREFEITURA DO RECIFE'), ('CARTAO CONSIGNADO', 'CARTAO CONSIGNADO'), ('CARTAO BENEFICIO', 'CARTAO BENEFICIO')], default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposta',
            name='orgao',
            field=models.CharField(choices=[('INSS', 'INSS'), ('FEDERAL', 'FEDERAL'), ('PREFEITURA DO RECIFE', 'PREFEITURA DO RECIFE'), ('GOVERNO DE PERNAMBUCO', 'GOVERNO DE PERNAMBUCO'), ('EXERCITO', 'EXERCITO'), ('AERONAUTICA', 'AERONAUTICA'), ('MARINHA', 'MARINHA')], default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposta',
            name='banco',
            field=models.CharField(choices=[('BMG', 'BMG'), ('ITAU', 'ITAU'), ('DAYCOVAL', 'DAYCOVAL'), ('C6 BANK', 'C6 BANK'), ('BANRISUL', 'BANRISUL'), ('MERCANTIL', 'MERCANTIL'), ('OLE CONSIGNADO', 'OLE CONSIGNADO'), ('BRADESCO', 'BRADESCO'), ('SAFRA', 'SAFRA')], max_length=60),
        ),
    ]
