# Generated by Django 5.0 on 2023-12-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_proposta_telefone_proposta_operacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticia', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='proposta',
            name='operacao',
            field=models.CharField(choices=[('NOVO', 'NOVO'), ('REFIN', 'REFIN'), ('PORTABILIDADE', 'PORTABILIDADE'), ('CARTAO CONSIGNADO', 'CARTAO CONSIGNADO'), ('CARTAO BENEFICIO', 'CARTAO BENEFICIO')], max_length=60),
        ),
    ]
